name: www.fivelements.it
favicon: null
layout_spectrum: 0.8605707616079599
typography_spectrum: 0.24541
title: Il non luogo ove trovare uno spazio per scoprire e ricostruire se stessi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71879e'
    - '#293239'
    - '#ffffff'
    - '#d0c4b4'
    - '#e9aa48'
  brandStrength: 0.16561414441093802
  lightness: 0.11881682300008833
  saturation: 0.9687008466571569
  rhythmicContrast: 0.8865768690593541
purpose: []
